/*©mit**************************************************************************
*                                                                              *
* This file is part of FRIEND UNIFYING PLATFORM.                               *
* Copyright (c) Friend Software Labs AS. All rights reserved.                  *
*                                                                              *
* Licensed under the Source EULA. Please refer to the copy of the MIT License, *
* found in the file license_mit.txt.                                           *
*                                                                              *
*****************************************************************************©*/

// Do not edit this file!

var server = {
	tls : {
		keyPath : 'path_to_key.pem',
		certPath : 'path_to_cert.pem',
		key : null,
		cert : null,
	},
	ws : {
		port : 6514,
	},
	friendcore : {
		host  : 'friendcore_host',
		port  : 6502,
	},
};

var shared = {
	rtc : {
		iceServers : [
			{
				urls : [
					"stun:stun_url.com:3478",
				],
			},
			{
				urls : [
					"turn:turn_url.com:3478",
				],
				username : 'turn_username',
				credential : 'turn_password',
			},
		],
	},
};

var conf = {
	shared : shared,
	server : server,
};

module.exports = conf;
