/*©mit**************************************************************************
*                                                                              *
* This file is part of FRIEND UNIFYING PLATFORM.                               *
* Copyright (c) Friend Software Labs AS. All rights reserved.                  *
*                                                                              *
* Licensed under the Source EULA. Please refer to the copy of the MIT License, *
* found in the file license_mit.txt.                                           *
*                                                                              *
*****************************************************************************©*/
/** @file
 *
 *  App Session
 *
 * file contain all functitons related to application sessions
 *
 *  @author PS (Pawel Stefanski)
 *  @date created 11/2016
 */
#include "sas_server.h"
#include <core/thread.h>
#include <system/systembase.h>
#include <limits.h>
#include <time.h>
#include <network/websocket_client.h>

/**
 * Create SASServer
 *
 * @return SAS server
 */

SASServer *SASServerNew()
{
	SASServer *serv = NULL;
	
	if( ( serv = FCalloc( 1, sizeof( SASServer ) ) ) != NULL )
	{
		
	}

	return serv;	
}

/**
 * Delete SASServer
 *
 * @param as pointer to SASServer
 */

void SASServerDelete( SASServer *sasser )
{
	if( sasser != NULL )
	{
		if( sasser->sass_IP != NULL )
		{
			FFree( sasser->sass_IP );
		}
		
		if( sasser->sass_UID != NULL )
		{
			FFree( sasser->sass_UID );
		}
		
		FFree( sasser );
	}
}

/**
 * Create shared app newssion
 *
 * @return application session
 */

SASSession *SASSessionNew( )
{
	SASSession *las = NULL;
	DEBUG("[SASSessionNew] Create app session\n");
	
	if( ( las = FCalloc( 1, sizeof( SASSession ) ) ) != NULL )
	{
		// ID is generated by database
	}
	else
	{
		FERROR("Cannot allocate memory for SASSessionNew\n");
	}
	DEBUG("[SASSessionNew] End\n");
	
	return las;
}

/**
 * Delete shared application session
 *
 * @param as pointer to session which will be deleted
 */

void SASSessionDelete( SASSession *as )
{
	DEBUG("[SASSessionDelete] Delete app session\n");
	if( as != NULL )
	{
		FFree( as );
	}
	DEBUG("[SASSessionDelete] App sessions deleted\n");
}
